import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Nav } from '@Components/nav/Nav'
import { Providers } from './Providers'
import { Toaster } from 'sonner'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Luks',
	description: 'Generated by create next app',
	icons: {
		icon: '/app.ico',
		apple: '/app.ico',
	},
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="es-Co">
			<body className={inter.className}>
				<Providers>
					{/* <Nav /> */}
					{children}
					<Toaster />
				</Providers>
			</body>
		</html>
	)
}
